---
- name: "roles/langs.go/tasks/main: Install latest go"
  become_user: isucon
  shell: |
    GO_VERSION=$(curl -s https://go.dev/VERSION?m=text | head -n 1) && \
    curl -LO "https://golang.org/dl/${GO_VERSION}.linux-amd64.tar.gz" && \
    sudo rm -rf /usr/local/go && \
    sudo tar -C /usr/local -xzf "${GO_VERSION}.linux-amd64.tar.gz" && \
    rm "${GO_VERSION}.linux-amd64.tar.gz" && \
    echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile

