---
- name: "roles/langs.go/tasks/main: Install latest go"
  become_user: isucon
  shell: |
    ARCH=$(uname -m) && [ "$ARCH" = "x86_64" ] && GO_ARCH="amd64" || GO_ARCH="arm64" && \
    GO_VERSION=$(curl -s https://go.dev/VERSION?m=text | head -n 1) && \
    INSTALL_DIR="/home/isucon/local" && \
    mkdir -p "$INSTALL_DIR" && \
    curl -LO "https://golang.org/dl/${GO_VERSION}.linux-${GO_ARCH}.tar.gz" && \
    rm -rf "${INSTALL_DIR}/go" && \
    tar -C "$INSTALL_DIR" -xzf "${GO_VERSION}.linux-${GO_ARCH}.tar.gz" && \
    rm "${GO_VERSION}.linux-${GO_ARCH}.tar.gz"

- name: "roles/langs.go/tasks/main: Add PATH for Go"
  become_user: isucon
  blockinfile:
    marker: "# {mark} ANSIBLE MANAGED BLOCK go"
    path: /home/isucon/.bashrc
    content: |
      export PATH=/home/isucon/local/go/bin:/home/isucon/go/bin:$PATH
      export GOROOT=/home/isucon/local/go
